# Generated by Django 5.2.8 on 2025-11-11 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('square_footage', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.SmallIntegerField(default=1)),
                ('bathrooms', models.SmallIntegerField(default=1)),
                ('balcony', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('dishwashing', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('own_heating', models.BooleanField(default=False)),
                ('parking_spot', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('sector', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('olx_url', models.URLField(unique=True)),
                ('storia_url', models.URLField(unique=True)),
                ('date_scraped', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_scraped'],
            },
        ),
        migrations.CreateModel(
            name='SavedApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApartmentProject.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'apartment')},
            },
        ),
    ]
